site_name: CODEX
theme:
  name: material
  icon:
    logo: material/asterisk-circle-outline
  favicon: assets/images/favico.png
  font:
    text: Space Mono
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - toc.follow
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - navigation.footer
    - content.code.copy
  plugins:
    - search
copyright: Made with ❤ by Aditya Deshmukh
extra:
  generator: false
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/scr33nslaver
    - icon: fontawesome/solid/paper-plane
      link: mailto:aadityadeshmukh@duck.com
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
nav:
  - Home: 'index.md'
  - Management: 
    - Management: 'Management/index.md'
    - PMBOK: 'Management/pmbok.md'
  - 'Agile Methodologies':
    - 'Agile Methodologies': 'Agile/index.md'
  - 'DevOps':
    - 'DevOps': 'DevOps/index.md'
    - 'Example Project': 'DevOps/devops-project.md'
  - Portfolio: 'resume.md'
