site_name: CODEX
theme:
  name: material
  icon:
    logo: fontawesome/solid/asterisk
  favicon: assets/images/favico.png
  font:
    text: Space Mono
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - toc.follow
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - navigation.footer
    - content.code.copy
  icon:
    tag:
      html: fontawesome/brands/html5
      js: fontawesome/brands/js
      css:  fontawesome/brands/css3
  plugins:
    - search
    - tags
copyright: Made with ❤ by Aditya Deshmukh
extra:
  generator: false
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/scr33nslaver
    - icon: fontawesome/solid/paper-plane
      link: mailto:aadityadeshmukh@duck.com
  tags:
    HTML5: html
    JavaScript: js
    CSS: css
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
nav:
  - Home: 'index.md'
  - Management: 
    - 'Management': 'Management/index.md'
  - 'Development':
    - 'Development': 'Development/index.md'
    - 'Databases':
      - 'PostgreSQL Quick Start': 'Development/postgre.md'
      - 'SQL': 'Development/sql.md'
    - 'Python':
      - 'Django Quick Start': 'Development/django.md'
      - 'Python database API': 'Development/python-database-api.md'
  - 'DevOps':
    - 'DevOps': 'DevOps/index.md'
  - 'Technologies':
    - 'Technologies': 'Technologies/index.md'
  - 'Portfolio': 'resume.md'
